### ISSUE TITLE
Persist task cancellation

### ISSUE THREAD

**Issue by brendanw** [lucas34/SwiftQueue#281] opened 2019-11-17 21:08 UTC
It'd be great if `SwiftQueueManager.cancelOperations(tag: String)` led to a persisted cancellation. The current behavior is the task is cancelled for the current session but resumes upon the app being restarted.

I think changing `SqOperationQueue.cancelOperations(tag: String)` to:

```
    func cancelOperations(tag: String) {
        for case let operation as SqOperation in operations where operation.info.tags.contains(tag) {
            operation.cancel()
            operation.remove()
            if operation.info.isPersisted {
                persister.remove(queueName: queue.name, taskId: operation.info.uuid)
            }
        }
    }
```

should do the trick. 

As an android developer used to WorkManager, thank you for putting this library together on iOS 🙏🙏

**Comment by lucas34** [comment] 2019-11-18 00:52
Hi,

This should already be the case, I also have a test cases 'testCancelWithTagShouldRemoveFromPersister' to verify this. Can you provide me an example when this is happening ?

**Comment by lucas34** [comment] 2019-11-21 05:45
Closing for now. Please re-open if you have a test case or sample. So far I can't reproduce

**Closed by lucas34** 2019-11-21 05:45 UTC
